markdown: kramdown
permalink: /blog/:year/:month/:day/:title
pages_dir: /pages
high_res_image: "/assets/images/chad_the_conqueror.141k.75.webp"
low_res_image: "/assets/images/chad_the_conqueror.14k.0.webp"
default_image: "/assets/images/chad_the_conqueror.141k.75.webp"
url: "https://chadthunderkok.com"
contacts:
  general: "/general-contact/"
  business: "/business-contact/"
social:
  x-twitter: "https://x.com/ch4dth0nd3rk0k"
  instagram: "https://instagram.com/chadwick_von_thunderkok"
  youtube: "https://www.youtube.com/@chadwickvonthunderkok"
exclude:
  - CNAME
  - Dockerfile
  - Makefile
  - README.md
  - tests
